language: go
sudo: required
go:
- 1.7
- 1.8
- tip
services:
- docker
env:
  matrix:
  - OKARCH=amd64 OSARCH=amd64
  - OKARCH=x86_64 OSARCH=x86_64
  - OKARCH=386 OSARCH=i386
  global:
  - VERSION=${TRAVIS_TAG}
  - GH_USER=${TRAVIS_REPO_SLUG%/*}
  - GH_APP=${TRAVIS_REPO_SLUG#*/}
  - JFROG_CLI_OFFER_CONFIG=false
  - secure: TbZYgDZrHnDuewVpZLQX7nDjAYIUtNEdLln4lyW4MhzM6GuIouARbgTcZsVRjEVFm5yP6YSHREOMF40Ka/t757nZMjWd7M1bmhMZz+vsdIG+/vrCPdUTLi+nq2Btm0JBjbgkBSM9gXA7j27YfOwsC63cRIRW0fPycSGLb8dsVyo4vKVtJkSoN65lA24uZ68DDJcS49YhESbje3T0Jmc3GoAIPpAnFdSNML7h/NtptteLntToSDgf4eafdUYJgA1zo2GJ5MWLjaWD/UbR7QigkePYmyJeiWFb3VPzu5+ag5YuBW5SdFjWZgc47B9s7q2/cOZrrK93izt7rNJruRdqIlFmwTKPxvivwKwNWBWrvwFWUIs1LOcES/yzDHvFZPrksnhrGwDOHenV6PWYuNOzFhNv0lw9SP4BF+Hi0SmMDmnT3bzmCsjfvuLf6hn38oX3SvdXb7QS1HJLnn95SD79aoxWIXXW9sBSmExZRvVGIl7mEJylk2Q9k3z6/QF9s+zoN2ZKAwKZer2LvWyCWdpbxn06hI8ovK3Cg/FnermeCauzceppmxXACrp0Fys8br5a/zLs3rI6guH1hKyoWfS/ewpysr8gj0Nuz+9+k7KJ37OnUJmc3izjwoyKxYayblLQU6FXiw1d1GdPY0U/oArXZf4dLh6FDYOX2WiDEWQfLrM=
before_install:
- sudo apt-get -qq update
- mkdir -p ${GOPATH}/bin
- cd ~
- curl https://glide.sh/get | sh
install:
- cd $GOPATH/src/github.com/${TRAVIS_REPO_SLUG}
- glide install
- go install
script:
- go test $(go list ./... | grep -v /vendor/)
before_deploy:
- docker pull fedora
- mkdir -p build/$OSARCH
- GOOS=linux GOARCH=$OKARCH go build --ldflags "-X main.VERSION=$VERSION" -o build/$OSARCH/$GH_APP
- cp $GOPATH/bin/go-bin-rpm tmp
- 'docker run -v $PWD:/mnt/travis fedora /bin/sh -c "cd /mnt/travis && (curl -sL https://bintray.com/bincrafters/public-rpm/rpm
  > /etc/yum.repos.d/w.repo) && dnf install go-bin-rpm changelog rpm-build -y --quiet
  && go-bin-rpm generate --file rpm.json -a $OSARCH --version $VERSION -o $GH_APP-$OSARCH-$VERSION.rpm"

'
- rm -rf ./tmp
- cp $GH_APP-$OSARCH-$VERSION.rpm $GH_APP-$OKARCH.rpm
- curl -fL https://getcli.jfrog.io | sh
- ./jfrog bt pc --key=$BTKEY --user=$GH_USER --licenses=MIT --vcs-url=https://github.com/$GH_USER/rpm
  $GH_USER/rpm/$GH_APP || echo "package already exists"
- "./jfrog bt upload --override=true --key $BTKEY --publish=true $GH_APP-$OSARCH-$VERSION.rpm
  $GH_USER/rpm/$GH_APP/$VERSION pool/$POOL/$GH_APP/"
- curl -X POST -u ${GH_USER}:${BTKEY} https://api.bintray.com/calc_metadata/${GH_USER}/rpm
deploy:
  provider: releases
  api_key:
    secure: jp0DvRNJkiTuBMlK2nAryROAXevFi6ha3ivoJPZ+0UgDuVrrMKlCBE7B0NAg7oBTXGSLLWZHpYTDlJVrjviiBiR6QpsV327qYxJ8iZ0rRtzhQniGKuSHfw1aOIyHaBCQa7YJNoGZVWJJRJ+Oxq1A18qxqEuirqn99AOJC/9EnCKE6RW3nUFGb6SQvXRd3uMj7hNizrjqib3TqhuVSXav9kPi70F0FmcRG1Lp+YfqcePWDEc3BdIjWWOx/JMQ3FhkMioINUcns9pky2fo1XWWJZu1MEHE+ENjGt0K4aRwuLAShDJs9M2SONVLoojrXAWBrpC2QCSgq3qf62bUiuI8XlScmS6YERmo4okn1zAyrlgZDjIGN/UqwPShItxXiE3ZNvI/ncy2fv/ETJ2pNzrpB0fivdF3OqXR9ehjxPl+MHCa7xPbd1pgJbGtXbOeRnTfHTUsEpWvJMa8nEDHO04jc2KSM3GId5lbmJbng95AxfIOfM7OpSHcVt/Kl/b4Z3EsktNqPX03bJVqTeXym9zemDIeqLTs3qe3+yX/JgB57Um7oie0clOSW0/gvLWjpko7iF21yJKUUrA6nEOfuX3BGvEILAl2FBt5Ngq5iQ9v024vRkyBqVqvk8R7RA599UmeUV5g8rwkzJBv+hemFY8zHiuKT6oVst/qSnnW9lIMs/I=
  file: ''
  on:
    repo: cmattoon/cli
